version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: "smartwaytesttask"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smartwaytesttask
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack

  web:
    build: .
    container_name: swtesttask
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
      